server:
  port: 80
spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://localhost:3306/mall?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=GMT%2B8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    database: MySQL
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        default_batch_fetch_size: 20
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_empty
    parser:
      allow-unquoted-control-chars: true
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 50MB
  data:
    redis:
      repositories:
        enabled: false

aliyun:
  oss:
    file:
      endpoint: oss-cn-beijing.aliyuncs.com
      key-id: LTAI5tKMbYzFdowxo7HyXd3Z
      key-secret: X7QEpjBZoSoSXxqbOijp9Tj1K7T6jl
      bucket-name: guli-edu-test-bucket

# Sa-Token 配置
sa-token:
  # token名称 (同时也是cookie名称)
  token-name: Authorization
  # token有效期，单位s 默认30天, -1代表永不过期
  timeout: 2592000
  # token临时有效期 (指定时间内无操作就视为token过期) 单位: 秒
  activity-timeout: 1800
  # 是否允许同一账号并发登录 (为true时允许一起登录, 为false时新登录挤掉旧登录)
  is-concurrent: false
  # 在多人登录同一账号时，是否共用一个token (为true时所有登录共用一个token, 为false时每次登录新建一个token)
  # token风格
  token-style: uuid
  is-read-cookie: false
  is-print: false





